version: "3.4"

services:
  app:
    image: such-a-lovely-js_app
    build: ./src
    ports:
      - ${APP_PORT}:31337
    command: >
      /wait-for postgres:5432 --timeout 5 -- node server.js
    env_file: .env
    depends_on: 
      - postgres
    restart: always

  postgres:
    image: stepan33314/such-a-lovely-js_postgres:latest
    build: ./postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  swagger:
    image: such-a-lovely-js__swagger
    build: ./swagger
    ports:
      - 8080:8080
    restart: always


volumes:
  db_volume:
