name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd src && npm install
    - name: Run ESLint
      run: cd src && ./node_modules/.bin/eslint src
    - name: Testing
      run: cd src && ./node_modules/.bin/jest
