name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd src && npm install
    - name: Run ESLint
      run: cd src && ./node_modules/.bin/eslint .
    - name: Testing
      run: cd src && ./node_modules/.bin/jest

  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [ test ]
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: make build
      - name: Publish Docker image
        run: make publish VERSION=1.12

  deploy:
    name: DEploy on master.yorchenko.rocks
    runs-on: ubuntu-18.04
    needs: [ test ]
    steps:
      - uses: actions/checkout@v1
      - name: Send Webhook
        run: curl http://internal.yorchenko.rocks/reload
